export enum DiscStyle {
  ROCK = 'Rock',
  POP = 'Pop',
  INDIE = 'Indie',
  JAZZ = 'Jazz',
  BLUES = 'Blues',
  CLASSICAL = 'Classical',
  ELECTRONIC = 'Electronic',
  HIP_HOP = 'Hip Hop',
  R_AND_B = 'R&B',
  COUNTRY = 'Country',
  REGGAE = 'Reggae',
  METAL = 'Metal',
  PUNK = 'Punk',
  FOLK = 'Folk',
  LATIN = 'Latin',
  MPB = 'MPB',
  SERTANEJO = 'Sertanejo',
  FUNK = 'Funk',
  SAMBA = 'Samba',
  BOSSA_NOVA = 'Bossa Nova',
}
